name: Node.js CI

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Set up SSH keys
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
          echo "This is the dev branch."
          echo "Performing actions for dev branch."
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${{ secrets.DEV_EC2_INSTANCE_HOSTNAMEDNS }} >> ~/.ssh/known_hosts
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
        elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "This is the main branch."
          echo "Performing actions for main branch."
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${{ secrets.PROD_EC2_INSTANCE_HOSTNAMEDNS }} >> ~/.ssh/known_hosts
          echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
        else
          echo "This branch is not supported."
        fi

    - name: Ensure SSH is installed on runner
      run: sudo apt-get install openssh-client -y

    - name: SSH, build and deploy
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
          echo "Connecting to dev instance via SSH"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.DEV_EC2_INSTANCE_HOSTNAMEDNS }} '
            cd /home/ubuntu/playible-polygon-interface &&
            git pull origin dev &&
            git checkout origin/dev &&
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm run build
            screen -S ${{ secrets.DEV_SCREEN_NAME }} -X stuff "^C"
            screen -S ${{ secrets.DEV_SCREEN_NAME }} -X stuff "npm run start$(printf \\r)"
            echo "Successfully deployed to dev instance."
          '
        elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "Connecting to production instance via SSH"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.PROD_EC2_INSTANCE_HOSTNAMEDNS }} '
            cd /home/ubuntu/playible-polygon-interface &&
            git pull origin main &&
            git checkout origin/main &&
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm run build
            screen -S ${{ secrets.PROD_SCREEN_NAME }} -X stuff "^C"
            screen -S ${{ secrets.PROD_SCREEN_NAME }} -X stuff "npm run start$(printf \\r)"
            echo "Successfully deployed to production instance."
          '
          fi
